-- DDL bootstrap script: create schemas
-- Replace <CATALOG_NAME> before execution.

CREATE SCHEMA IF NOT EXISTS <CATALOG_NAME>.landing;
CREATE SCHEMA IF NOT EXISTS <CATALOG_NAME>.bronze;
CREATE SCHEMA IF NOT EXISTS <CATALOG_NAME>.silver;
CREATE SCHEMA IF NOT EXISTS <CATALOG_NAME>.gold;
